name: biruni_connect
description: "A new Flutter project."
publish_to: "none" # Bu projenin pub.dev'e yayınlanmayacağını belirtir.

version: 1.0.0+1 # Uygulamanın sürüm numarası (major.minor.patch+build)

environment:
  sdk: ^3.5.3 # Flutter SDK sürümü için minimum gereksinimler.

dependencies:
  flutter:
    sdk: flutter # Flutter SDK'sını belirtir.

  # State Management (Durum yönetimi için kullanılan paketler)
  flutter_bloc: ^8.1.3 # Flutter için BLoC mimarisi
  bloc: ^8.1.2 # BLoC kütüphanesi (arka plan işlevsellik)

  # Dependency Injection (Bağımlılık enjeksiyonu için kullanılan paketler)
  get_it: ^8.0.2 # Bağımlılık enjeksiyonu yöneticisi
  injectable: ^2.3.2 # Kod üretiminde bağımlılık enjeksiyonu için yardımcı

  # Routing (Sayfa yönlendirmesi için kullanılan paketler)
  auto_route: ^9.2.2 # Otomatik yönlendirme sağlayan bir yapı

  # Network (Ağ bağlantıları için kullanılan paketler)
  dio: ^5.4.0 # HTTP istekleri için güçlü bir istemci
  retrofit: ^4.0.3 # REST API entegrasyonu için basitleştirilmiş yapı
  internet_connection_checker: ^1.0.0+1 # İnternet bağlantı durumu kontrolü

  # Local Storage (Yerel veri saklama)
  shared_preferences: ^2.2.2 # Anahtar-değer tabanlı veri saklama
  hive_flutter: ^1.1.0 # Hızlı ve basit bir yerel veritabanı çözümü

  # Utils (Yardımcı araçlar)
  dartz: ^0.10.1 # Functional programming araçları (Option, Either gibi)
  equatable: ^2.0.7 # Nesnelerin karşılaştırılmasını kolaylaştırır
  json_annotation: ^4.8.1 # JSON serileştirme/deserileştirme desteği
  freezed_annotation: ^2.4.1 # Immutable veri sınıfları için anotasyon

  # Flutter Cupertino Icons (iOS stilinde ikonlar)
  cupertino_icons: ^1.0.8 # Cupertino tabanlı simgeler

  # Navigation (Gezinme için alternatif yapı)
  go_router: ^14.6.1 # URL tabanlı gezinme yapısı
  carousel_slider: ^5.0.0
  url_launcher: ^6.2.5
  webview_flutter: ^4.10.0
  flutter_launcher_icons: ^0.14.1
  intl: ^0.20.1

  # SVG desteği
  flutter_svg: ^2.0.16 # SVG dosyalarını görüntülemek için destek

dev_dependencies:
  flutter_test:
    sdk: flutter # Flutter'ın test framework'ü

  # Code Generation (Kod üretimi için kullanılan araçlar)
  build_runner: ^2.4.7 # Kod üretimi işlemleri için ana araç
  auto_route_generator: ^9.0.0 # AutoRoute için kod üretimi
  injectable_generator: ^2.4.1 # Injectable için kod üretimi
  json_serializable: ^6.7.1 # JSON işlemleri için kod üretimi
  freezed: ^2.4.6 # Freezed yapılarını otomatik oluşturur
  retrofit_generator: ^9.1.5 # Retrofit için kod üretimi

  # Linting ve analiz araçları
  flutter_lints: ^5.0.0 # Flutter için varsayılan lint kuralları
  very_good_analysis: ^6.0.0 # Ekstra analiz kuralları

flutter:
  uses-material-design: true # Material Design öğelerini etkinleştirir.

  # Uygulamada kullanılan varlıklar
  assets:
    - assets/images/logo/
    - assets/images/university/
    - assets/images/announcements/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app/logo.png"
  image_path_android: "assets/images/app/logo.png"
  image_path_ios: "assets/images/app/logo.png"
  adaptive_icon_background: "#ffffff" # veya istediğiniz renk
  adaptive_icon_foreground: "assets/images/app/logo.png"
  remove_alpha_ios: true
